# Generated by Django 2.2.6 on 2019-11-03 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('PC', 'PC'), ('OFFERS', 'Offers'), ('OTHERS', 'Others')], default='OTHERS', max_length=20)),
                ('link', models.URLField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
