# Generated by Django 2.2.6 on 2019-12-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ANDROID', 'Android'), ('PC', 'PC'), ('Machine Learning', 'Machine Learning'), ('OFFERS', 'Offers'), ('OTHERS', 'Others')], default='OTHERS', max_length=20),
        ),
    ]
