# Generated by Django 2.2.6 on 2020-01-25 12:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_home_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
